name: terraform-destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type DESTROY to confirm'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: envs/primary
      TF_VAR_aws_region: ${{ secrets.TF_VAR_aws_region }}
      TF_VAR_name_prefix: ${{ secrets.TF_VAR_name_prefix }}
      TF_VAR_db_username: ${{ secrets.TF_VAR_db_username }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
      TF_VAR_app_instance_profile: ${{ secrets.TF_VAR_app_instance_profile }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Block unless confirmed
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "DESTROY" ]; then
            echo "Confirmation failed. You must type DESTROY."
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::132672187356:role/github-actions-terraform-r360
          aws-region: us-east-1

      - name: Terraform init
        working-directory: envs/primary
        run: terraform init -input=false

      - name: Terraform destroy
        working-directory: envs/primary
        run: terraform destroy -auto-approve -input=false
