jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: envs/primary
      TF_VAR_aws_region: ${{ secrets.TF_VAR_aws_region }}
      TF_VAR_name_prefix: ${{ secrets.TF_VAR_name_prefix }}
      TF_VAR_db_username: ${{ secrets.TF_VAR_db_username }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
      TF_VAR_app_instance_profile: ${{ secrets.TF_VAR_app_instance_profile }}

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Block unless confirmed
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "DESTROY" ]; then
            echo "Confirmation failed. You must type DESTROY."
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
