name: terraform-apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/primary

    env:
      TF_VAR_aws_region: ${{ secrets.TF_VAR_aws_region }}
      TF_VAR_name_prefix: ${{ secrets.TF_VAR_name_prefix }}
      TF_VAR_db_master_username: ${{ secrets.TF_VAR_db_master_username }}
      TF_VAR_db_master_password: ${{ secrets.TF_VAR_db_master_password }}
      TF_VAR_app_instance_profile: ${{ secrets.TF_VAR_app_instance_profile }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::132672187356:role/github-actions-terraform-r360
          aws-region: us-east-1

      - name: Who am I in AWS?
        run: |
          aws sts get-caller-identity
          echo "AWS_REGION=$AWS_REGION"
          echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false
